# Page settings

baseurl = "http://resume.matthewvanderhoff.com/"
languageCode = "en-us"
title = "Matthew Vander Hoff Resume"
theme = "hugo-orbit-theme"

# Do not build files for websites. Need them? Set to false
disableRSS = true
disableSitemap = true
disable404 = true

[params]

# Meta
    description = "Information Security professional"
    author = "Matthew Vander Hoff"

# Theme styles

    # The original template comes with 6 colour schemes. You may choose styles below.
    # "styles.css", "styles-2.css", "styles-3.css", "styles-4.css", "styles-5.css", "styles-6.css"
    # are available. Also the source LESS files are included so
    # it’s quick and easy to change the styling and colour scheme.

    styles = "styles.css"

# Sidebar sections

    # Profile section
    [params.profile]
        name = "Matthew Vander Hoff"
        tagline = "Information Security Professional"
        avatar = "matt.png"

    # Contact section
    [params.contact]
        enable = true

        [[params.contact.list]]
        class = "email"
        icon = "fa-envelope"
        url = "mailto: jobs@matthewvanderhoff.com"
        title = "jobs@matthewvanderhoff.com"

        # [[params.contact.list]]
        # class = "phone"
        # icon = "fa-phone"
        # url = "tel:+9803132909"
        # title = "+1234567890"

        [[params.contact.list]]
        class = "website"
        icon = "fa-globe"
        url = "//matthewvanderhoff.com"
        title = "matthewvanderhoff.com"

        [[params.contact.list]]
        class = "linkedin"
        icon = "fa-linkedin"
        url = "//linkedin.com/in/matthew-vander-hoff-96363064/"
        title = "linkedin.com"

        [[params.contact.list]]
        class = "github"
        icon = "fa-github"
        url = "//github.com/vanderh0ff"
        title = "github.com/vanderh0ff"

        [[params.contact.list]]
        class = "twitter"
        icon = "fa-twitter"
        url = "//twitter.com/h0ffline"
        title = "@h0ffline"

    # Education section
    [params.education]
        enable = true
        title = "Education"

        [[params.education.list]]
        degree = "BA in Computer Science focus in Cyber Security"
        college = "University of North Carolina Charlotte"
        dates = "2012 - 2016"

    # Languages section
    [params.languages]
        enable = true
        title = "Languages"

        [[params.languages.list]]
        language = "English"
        level = "Native"

    # Interests section
    [params.interests]
        enable = true
        title = "Interests"

        [[params.interests.list]]
        interest = "reverse engineering"

        [[params.interests.list]]
        interest = "web exploitation"

        [[params.interests.list]]
        interest = "data visualization"

        [[params.interests.list]]
        interest = "Snowboarding"

        [[params.interests.list]]
        interest = "Cooking"

        [[params.interests.list]]
        interest = "CTFs"



# Main body sections

    # You may use markdown in summary, details and intro fields. But don't overdose, it's resume!:)

    # Summary section
    [params.summary]
        enable = true
        icon = "fa-user"
        title = "Career goals"
        summary = "As an Information Security professional I hope to be constantly challenged in my job and solve complex challenges as a member of a team. I enjoy working in Information Security because it requires continuous learning and it has introduced me to many passionate individuals that are wiling to help."

    # Experiences section
    [params.experiences]
        enable = true
        icon = "fa-briefcase"
        title = "Experiences"

        [[params.jobs.list]]
        position = "Information Security Analysit Intern"
        dates = "Jan, 2016 - Dec, 2016"
        company = "University of North Carolina Charlotte, Charlotte NC"
        details = "As a member of the security team I helped migrate our SIEM from LogRythm to Splunk. This process invloved creating and refining alerts to replicate privious functions, creating TAs and other code to achive desired functionality. I also designed a scaleable NIDS infrastructure using Ansible, Suricata, and old servers to evaluate benifits of internal network monitoring. I was also responsible for training other members of the team on how to update and maintain the network monitoring system. I was the primary team member for automating workflows and creating scripts."

        [[params.jobs.list]]
        position = "Systems Administrator"
        dates = "Sep, 2013 - Aug, 2014"
        company = "Ace Motor Acceptance Corp, Charlotte NC"
        details = "Managed an Active Directory Domain using windows server 2012r2 and HyperV clusters with failover, Ensured data retention with Synology SAN devices, after hours upgrades with RDP and SSH, mitigated cryptolocker infection due to proper backup policy. Created a SIEM using Elastic Search, Logstash, and Kibana (ELK) to streamline interactions with security onion."

        [[params.jobs.list]]
        position = "Systems Administrator"
        dates = "2011 - 2012"
        company = "Coffe Shop Millionaire, Remote"
        details = "Developed a python software as a service (SaaS) using the Django framework providing users with a convenient listing of websites for sale with useful purchasing data including price, Alexa rank, and if monetization services like AdSense were on the site to find low cost sites with high traffic and monetize them. Also updated and maintained an e-learning website and converted Photoshop mockups to functioning sites."

    # Projects section
    [params.projects]
        enable = true
        icon = "fa-archive"
        title = "Projects"
        intro = "Opensource projects that I work on"

        [[params.projects.list]]
        title = "iamtoolazy"
        url = "https://github.com/vanderh0ff/iamtoolazy"
        tagline = "python web interface for Hacklet iot outlets, for when your too lazy to get up and turn off that light"
        [[params.projects.list]]
        title = "learn linux"
        url = "https://github.com/vanderh0ff/learnlinux"
        tagline = "Interactive Linux tutorial, just clone and follow along. Written in Markdown with exercises in Bash"

    # Skills section
    [params.skills]
        enable = true
        icon = "fa-rocket"
        title = "Skills & Proficiency"

        [[params.skills.list]]
        skill = "Python"
        level = "80%"
        [[params.skills.list]]
        skill = "Bash"
        level = "80%"
        [[params.skills.list]]
        skill = "Linux"
        level = "80%"
        [[params.skills.list]]
        skill = "Splunk"
        level = "75%"
        [[params.skills.list]]
        skill = "Web Application Exploitation"
        level = "70%"
        [[params.skills.list]]
        skill = "Django"
        level = "40%"
        [[params.skills.list]]
        skill = "C"
        level = "10%"
        [[params.skills.list]]
        skill = "x86 assembly"
        level = "10%"
        [[params.skills.list]]
        skill = "arm assembly"
        level = "10%"
    # Footer section

    # The original template is released under the Creative Commons Attribution 3.0 License.
    # Please keep the original attribution link when using for your own project.
    # If you'd like to use the template without the attribution,
    # you can check out other license options via template author's website: themes.3rdwavemedia.com
    #
    # As for Hugo port you may rewrite the "Ported for..." line with setting your name below.

    [params.footer]
        copyright = "Ported for Matthew Vander Hoff"
